// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScheduler.API.Data;

#nullable disable

namespace SmartScheduler.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517004011_Sprint3_Constraints_SeedData")]
    partial class Sprint3_Constraints_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartScheduler.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasLab")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "D Blok",
                            Capacity = 60,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "D-101"
                        },
                        new
                        {
                            Id = 2,
                            Building = "D Blok",
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "D-201"
                        },
                        new
                        {
                            Id = 3,
                            Building = "Laboratuvar Binası",
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = true,
                            HasProjector = true,
                            Name = "LAB-1"
                        },
                        new
                        {
                            Id = 4,
                            Building = "A Blok",
                            Capacity = 80,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "A-105"
                        },
                        new
                        {
                            Id = 5,
                            Building = "Laboratuvar Binası",
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = true,
                            HasProjector = true,
                            Name = "LAB-2"
                        },
                        new
                        {
                            Id = 6,
                            Building = "B Blok",
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "B-301"
                        },
                        new
                        {
                            Id = 7,
                            Building = "C Blok",
                            Capacity = 45,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "C-102"
                        },
                        new
                        {
                            Id = 8,
                            Building = "Amfi Binası",
                            Capacity = 150,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "AMFİ-1"
                        },
                        new
                        {
                            Id = 9,
                            Building = "Laboratuvar Binası",
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = true,
                            HasProjector = true,
                            Name = "LAB-3"
                        },
                        new
                        {
                            Id = 10,
                            Building = "D Blok",
                            Capacity = 55,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "D-102"
                        },
                        new
                        {
                            Id = 11,
                            Building = "A Blok",
                            Capacity = 70,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "A-201"
                        },
                        new
                        {
                            Id = 12,
                            Building = "Laboratuvar Binası",
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = true,
                            HasProjector = true,
                            Name = "LAB-4"
                        },
                        new
                        {
                            Id = 13,
                            Building = "B Blok",
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "B-102"
                        },
                        new
                        {
                            Id = 14,
                            Building = "C Blok",
                            Capacity = 60,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "C-201"
                        },
                        new
                        {
                            Id = 15,
                            Building = "Amfi Binası",
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HasLab = false,
                            HasProjector = true,
                            Name = "AMFİ-2"
                        });
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Constraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId", "ClassroomId")
                        .IsUnique();

                    b.ToTable("Constraints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 3,
                            CourseId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Lab bilgisayarı gerektirir"
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 9,
                            CourseId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Lab bilgisayarı gerektirir"
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 12,
                            CourseId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Lab bilgisayarı gerektirir"
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 3,
                            CourseId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Mobil geliştirme ortamı gerektirir"
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 5,
                            CourseId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Mobil geliştirme ortamı gerektirir"
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 9,
                            CourseId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Mobil geliştirme ortamı gerektirir"
                        },
                        new
                        {
                            Id = 7,
                            ClassroomId = 9,
                            CourseId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "GPU destekli lab gerektirir"
                        },
                        new
                        {
                            Id = 8,
                            ClassroomId = 12,
                            CourseId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "GPU destekli lab gerektirir"
                        },
                        new
                        {
                            Id = 9,
                            ClassroomId = 3,
                            CourseId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "İzole ağ ortamı gerektirir"
                        },
                        new
                        {
                            Id = 10,
                            ClassroomId = 5,
                            CourseId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "İzole ağ ortamı gerektirir"
                        },
                        new
                        {
                            Id = 11,
                            ClassroomId = 5,
                            CourseId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "GPU lab gerektirir"
                        },
                        new
                        {
                            Id = 12,
                            ClassroomId = 12,
                            CourseId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "GPU lab gerektirir"
                        },
                        new
                        {
                            Id = 13,
                            ClassroomId = 5,
                            CourseId = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Donanım lab gerektirir"
                        },
                        new
                        {
                            Id = 14,
                            ClassroomId = 12,
                            CourseId = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Donanım lab gerektirir"
                        },
                        new
                        {
                            Id = 15,
                            ClassroomId = 4,
                            CourseId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Yüksek kapasiteli sınıf gerektirir"
                        },
                        new
                        {
                            Id = 16,
                            ClassroomId = 11,
                            CourseId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Yüksek kapasiteli sınıf gerektirir"
                        },
                        new
                        {
                            Id = 17,
                            ClassroomId = 8,
                            CourseId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Yüksek kapasiteli sınıf gerektirir"
                        },
                        new
                        {
                            Id = 18,
                            ClassroomId = 4,
                            CourseId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Yüksek kapasiteli sınıf gerektirir"
                        },
                        new
                        {
                            Id = 19,
                            ClassroomId = 8,
                            CourseId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Yüksek kapasiteli sınıf gerektirir"
                        },
                        new
                        {
                            Id = 20,
                            ClassroomId = 8,
                            CourseId = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Amfi gerektirir"
                        },
                        new
                        {
                            Id = 21,
                            ClassroomId = 15,
                            CourseId = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Amfi gerektirir"
                        });
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CS301",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 1,
                            Name = "Yazılım Mühendisliği",
                            StudentCount = 60
                        },
                        new
                        {
                            Id = 2,
                            Code = "CS302",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 2,
                            Name = "Veri Tabanı Sistemleri",
                            StudentCount = 45
                        },
                        new
                        {
                            Id = 3,
                            Code = "CS303",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 3,
                            Name = "Algoritma Analizi",
                            StudentCount = 55
                        },
                        new
                        {
                            Id = 4,
                            Code = "CS304",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 1,
                            Name = "Yapay Zeka",
                            StudentCount = 40
                        },
                        new
                        {
                            Id = 5,
                            Code = "CS305",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 4,
                            Name = "Bilgisayar Ağları",
                            StudentCount = 50
                        },
                        new
                        {
                            Id = 6,
                            Code = "CS306",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 5,
                            Name = "İşletim Sistemleri",
                            StudentCount = 65
                        },
                        new
                        {
                            Id = 7,
                            Code = "CS307",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 9,
                            Name = "Veri Yapıları",
                            StudentCount = 70
                        },
                        new
                        {
                            Id = 8,
                            Code = "CS308",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 6,
                            Name = "Nesne Yönelimli Programlama",
                            StudentCount = 55
                        },
                        new
                        {
                            Id = 9,
                            Code = "CS309",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 8,
                            Name = "Web Programlama",
                            StudentCount = 45
                        },
                        new
                        {
                            Id = 10,
                            Code = "CS310",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 11,
                            Name = "Mobil Uygulama Geliştirme",
                            StudentCount = 35
                        },
                        new
                        {
                            Id = 11,
                            Code = "CS311",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 2,
                            Name = "Makine Öğrenmesi",
                            StudentCount = 40
                        },
                        new
                        {
                            Id = 12,
                            Code = "CS312",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 13,
                            Name = "Siber Güvenlik",
                            StudentCount = 30
                        },
                        new
                        {
                            Id = 13,
                            Code = "CS313",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 14,
                            Name = "Bulut Bilişim",
                            StudentCount = 38
                        },
                        new
                        {
                            Id = 14,
                            Code = "CS314",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 2,
                            Name = "Derin Öğrenme",
                            StudentCount = 25
                        },
                        new
                        {
                            Id = 15,
                            Code = "CS315",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 3,
                            Name = "Sistem Programlama",
                            StudentCount = 50
                        },
                        new
                        {
                            Id = 16,
                            Code = "CS316",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 7,
                            Name = "Derleyici Tasarımı",
                            StudentCount = 35
                        },
                        new
                        {
                            Id = 17,
                            Code = "CS317",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 15,
                            Name = "Paralel Programlama",
                            StudentCount = 30
                        },
                        new
                        {
                            Id = 18,
                            Code = "CS318",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 3,
                            InstructorId = 12,
                            Name = "Bilgisayar Grafikleri",
                            StudentCount = 40
                        },
                        new
                        {
                            Id = 19,
                            Code = "CS319",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 4,
                            InstructorId = 5,
                            Name = "Gömülü Sistemler",
                            StudentCount = 28
                        },
                        new
                        {
                            Id = 20,
                            Code = "CS320",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Credit = 2,
                            InstructorId = 10,
                            Name = "Proje Yönetimi",
                            StudentCount = 80
                        });
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "ahmet.yilmaz@uni.edu.tr",
                            Name = "Ahmet Yılmaz",
                            Title = "Prof. Dr."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "ayse.kaya@uni.edu.tr",
                            Name = "Ayşe Kaya",
                            Title = "Doç. Dr."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "mehmet.demir@uni.edu.tr",
                            Name = "Mehmet Demir",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "fatma.sahin@uni.edu.tr",
                            Name = "Fatma Şahin",
                            Title = "Doç. Dr."
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Elektrik-Elektronik Müh.",
                            Email = "ali.celik@uni.edu.tr",
                            Name = "Ali Çelik",
                            Title = "Prof. Dr."
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "zeynep.arslan@uni.edu.tr",
                            Name = "Zeynep Arslan",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Matematik",
                            Email = "hasan.kilic@uni.edu.tr",
                            Name = "Hasan Kılıç",
                            Title = "Doç. Dr."
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "elif.yildiz@uni.edu.tr",
                            Name = "Elif Yıldız",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "mustafa.ozturk@uni.edu.tr",
                            Name = "Mustafa Öztürk",
                            Title = "Prof. Dr."
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Endüstri Mühendisliği",
                            Email = "selin.aydin@uni.edu.tr",
                            Name = "Selin Aydın",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "burak.gunes@uni.edu.tr",
                            Name = "Burak Güneş",
                            Title = "Doç. Dr."
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "merve.koc@uni.edu.tr",
                            Name = "Merve Koç",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Yazılım Mühendisliği",
                            Email = "emre.yilmaz@uni.edu.tr",
                            Name = "Emre Yılmaz",
                            Title = "Prof. Dr."
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "ceren.dogan@uni.edu.tr",
                            Name = "Ceren Doğan",
                            Title = "Dr. Öğr. Üyesi"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Bilgisayar Mühendisliği",
                            Email = "tarik.sen@uni.edu.tr",
                            Name = "Tarık Şen",
                            Title = "Doç. Dr."
                        });
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("FitnessScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.ScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Constraint", b =>
                {
                    b.HasOne("SmartScheduler.API.Models.Classroom", "Classroom")
                        .WithMany("Constraints")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartScheduler.API.Models.Course", "Course")
                        .WithMany("Constraints")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Course", b =>
                {
                    b.HasOne("SmartScheduler.API.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.ScheduleEntry", b =>
                {
                    b.HasOne("SmartScheduler.API.Models.Classroom", "Classroom")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduler.API.Models.Course", "Course")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduler.API.Models.Schedule", "Schedule")
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Classroom", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Course", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SmartScheduler.API.Models.Schedule", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
